# Railway Configuration File
# Defines how Railway should build and deploy your FastAPI application

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Resource limits (optional - Railway auto-scales by default)
# Uncomment and adjust based on your needs
# [deploy.resources]
# memoryLimit = 2048  # MB
# cpuLimit = 1000     # millicores (1000 = 1 vCPU)
