# Railway Configuration File
# Tells Railway to use Docker instead of Nixpacks

[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"
watchPatterns = ["api/**"]

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
